language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4.0
  - ruby-head
script: 'bundle exec rspec spec'
before_install: gem install bundler -v 1.14.3
notifications:
  slack:
    secure: CYxJDs0jJkrgXfbOyHuF+gJtxgK5JjS0GAFRNOlkWlDUmpEErtcnPuBOrlzkIBJS4eXaDOuSvpyRJSuJZJjEhmp94GEI98GEcyvByHuaehUWhzhUrhXstX/gg/Ntt6jiFR5dC6NrRWAnmKb7cDsfvagGAVNAuNzAtX0Z9iXWQDo=
